# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='db_service.proto',
    package='',
    syntax='proto3',
    serialized_options=b'\n\nuz.globens',
    serialized_pb=b'\n\x10\x64\x62_service.proto\"\xd0\x01\n\x10\x41uthenticateUser\x1a\x8e\x01\n\x07Request\x12\x34\n\x06method\x18\x01 \x01(\x0e\x32$.AuthenticateUser.Request.AuthMethod\x12\x0b\n\x03key\x18\x02 \x01(\t\"@\n\nAuthMethod\x12\n\n\x06GOOGLE\x10\x00\x12\x0c\n\x08\x46\x41\x43\x45\x42OOK\x10\x01\x12\r\n\tKAKAOTALK\x10\x03\x12\t\n\x05PHONE\x10\x04\x1a+\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06userId\x18\x02 \x01(\x05\"U\n\x0e\x44\x65\x61\x63tivateUser\x1a&\n\x07Request\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\x1a\x1b\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa4\x01\n\x0eGlobensService\x12K\n\x10\x61uthenticateUser\x12\x19.AuthenticateUser.Request\x1a\x1a.AuthenticateUser.Response\"\x00\x12\x45\n\x0e\x64\x65\x61\x63tivateUser\x12\x17.DeactivateUser.Request\x1a\x18.DeactivateUser.Response\"\x00\x42\x0c\n\nuz.globensb\x06proto3'
)

_AUTHENTICATEUSER_REQUEST_AUTHMETHOD = _descriptor.EnumDescriptor(
    name='AuthMethod',
    full_name='AuthenticateUser.Request.AuthMethod',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='GOOGLE', index=0, number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='FACEBOOK', index=1, number=1,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='KAKAOTALK', index=2, number=3,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='PHONE', index=3, number=4,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=120,
    serialized_end=184,
)
_sym_db.RegisterEnumDescriptor(_AUTHENTICATEUSER_REQUEST_AUTHMETHOD)

_AUTHENTICATEUSER_REQUEST = _descriptor.Descriptor(
    name='Request',
    full_name='AuthenticateUser.Request',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='method', full_name='AuthenticateUser.Request.method', index=0,
            number=1, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='key', full_name='AuthenticateUser.Request.key', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _AUTHENTICATEUSER_REQUEST_AUTHMETHOD,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=42,
    serialized_end=184,
)

_AUTHENTICATEUSER_RESPONSE = _descriptor.Descriptor(
    name='Response',
    full_name='AuthenticateUser.Response',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='success', full_name='AuthenticateUser.Response.success', index=0,
            number=1, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='userId', full_name='AuthenticateUser.Response.userId', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=186,
    serialized_end=229,
)

_AUTHENTICATEUSER = _descriptor.Descriptor(
    name='AuthenticateUser',
    full_name='AuthenticateUser',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[_AUTHENTICATEUSER_REQUEST, _AUTHENTICATEUSER_RESPONSE, ],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=21,
    serialized_end=229,
)

_DEACTIVATEUSER_REQUEST = _descriptor.Descriptor(
    name='Request',
    full_name='DeactivateUser.Request',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='userId', full_name='DeactivateUser.Request.userId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='key', full_name='DeactivateUser.Request.key', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=249,
    serialized_end=287,
)

_DEACTIVATEUSER_RESPONSE = _descriptor.Descriptor(
    name='Response',
    full_name='DeactivateUser.Response',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='success', full_name='DeactivateUser.Response.success', index=0,
            number=1, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=186,
    serialized_end=213,
)

_DEACTIVATEUSER = _descriptor.Descriptor(
    name='DeactivateUser',
    full_name='DeactivateUser',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[_DEACTIVATEUSER_REQUEST, _DEACTIVATEUSER_RESPONSE, ],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=231,
    serialized_end=316,
)

_AUTHENTICATEUSER_REQUEST.fields_by_name['method'].enum_type = _AUTHENTICATEUSER_REQUEST_AUTHMETHOD
_AUTHENTICATEUSER_REQUEST.containing_type = _AUTHENTICATEUSER
_AUTHENTICATEUSER_REQUEST_AUTHMETHOD.containing_type = _AUTHENTICATEUSER_REQUEST
_AUTHENTICATEUSER_RESPONSE.containing_type = _AUTHENTICATEUSER
_DEACTIVATEUSER_REQUEST.containing_type = _DEACTIVATEUSER
_DEACTIVATEUSER_RESPONSE.containing_type = _DEACTIVATEUSER
DESCRIPTOR.message_types_by_name['AuthenticateUser'] = _AUTHENTICATEUSER
DESCRIPTOR.message_types_by_name['DeactivateUser'] = _DEACTIVATEUSER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthenticateUser = _reflection.GeneratedProtocolMessageType('AuthenticateUser', (_message.Message,), {

    'Request': _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
        'DESCRIPTOR': _AUTHENTICATEUSER_REQUEST,
        '__module__': 'db_service_pb2'
        # @@protoc_insertion_point(class_scope:AuthenticateUser.Request)
    })
    ,

    'Response': _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
        'DESCRIPTOR': _AUTHENTICATEUSER_RESPONSE,
        '__module__': 'db_service_pb2'
        # @@protoc_insertion_point(class_scope:AuthenticateUser.Response)
    })
    ,
    'DESCRIPTOR': _AUTHENTICATEUSER,
    '__module__': 'db_service_pb2'
    # @@protoc_insertion_point(class_scope:AuthenticateUser)
})
_sym_db.RegisterMessage(AuthenticateUser)
_sym_db.RegisterMessage(AuthenticateUser.Request)
_sym_db.RegisterMessage(AuthenticateUser.Response)

DeactivateUser = _reflection.GeneratedProtocolMessageType('DeactivateUser', (_message.Message,), {

    'Request': _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
        'DESCRIPTOR': _DEACTIVATEUSER_REQUEST,
        '__module__': 'db_service_pb2'
        # @@protoc_insertion_point(class_scope:DeactivateUser.Request)
    })
    ,

    'Response': _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
        'DESCRIPTOR': _DEACTIVATEUSER_RESPONSE,
        '__module__': 'db_service_pb2'
        # @@protoc_insertion_point(class_scope:DeactivateUser.Response)
    })
    ,
    'DESCRIPTOR': _DEACTIVATEUSER,
    '__module__': 'db_service_pb2'
    # @@protoc_insertion_point(class_scope:DeactivateUser)
})
_sym_db.RegisterMessage(DeactivateUser)
_sym_db.RegisterMessage(DeactivateUser.Request)
_sym_db.RegisterMessage(DeactivateUser.Response)

DESCRIPTOR._options = None

_GLOBENSSERVICE = _descriptor.ServiceDescriptor(
    name='GlobensService',
    full_name='GlobensService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=319,
    serialized_end=483,
    methods=[
        _descriptor.MethodDescriptor(
            name='authenticateUser',
            full_name='GlobensService.authenticateUser',
            index=0,
            containing_service=None,
            input_type=_AUTHENTICATEUSER_REQUEST,
            output_type=_AUTHENTICATEUSER_RESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='deactivateUser',
            full_name='GlobensService.deactivateUser',
            index=1,
            containing_service=None,
            input_type=_DEACTIVATEUSER_REQUEST,
            output_type=_DEACTIVATEUSER_RESPONSE,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_GLOBENSSERVICE)

DESCRIPTOR.services_by_name['GlobensService'] = _GLOBENSSERVICE

# @@protoc_insertion_point(module_scope)
