# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import db_service_pb2 as db__service__pb2


class GlobensServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.authenticateUser = channel.unary_unary(
            '/GlobensService/authenticateUser',
            request_serializer=db__service__pb2.AuthenticateUser.Request.SerializeToString,
            response_deserializer=db__service__pb2.AuthenticateUser.Response.FromString,
        )
        self.deactivateUser = channel.unary_unary(
            '/GlobensService/deactivateUser',
            request_serializer=db__service__pb2.DeactivateUser.Request.SerializeToString,
            response_deserializer=db__service__pb2.DeactivateUser.Response.FromString,
        )


class GlobensServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def authenticateUser(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deactivateUser(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlobensServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'authenticateUser': grpc.unary_unary_rpc_method_handler(
            servicer.authenticateUser,
            request_deserializer=db__service__pb2.AuthenticateUser.Request.FromString,
            response_serializer=db__service__pb2.AuthenticateUser.Response.SerializeToString,
        ),
        'deactivateUser': grpc.unary_unary_rpc_method_handler(
            servicer.deactivateUser,
            request_deserializer=db__service__pb2.DeactivateUser.Request.FromString,
            response_serializer=db__service__pb2.DeactivateUser.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'GlobensService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
